server:
  port: 8090 

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXXXXX/XXXb?useSSL=false&useUnicode=true
    username: XXX
    password: XXX

  ## JPA Setting Info
  jpa:
    show_sql: true  # sql 쿼리를 보여줍니다.
    hibernate:
      ddl-auto: update  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
        enable_lazy_load_no_trans: true
